In [1]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN
import matplotlib.pyplot as plt
import numpy as np

In [4]:
df=pd.read_csv("/content/tel_churn (1).csv")
df.head()

Unnamed: 0  SeniorCitizen  MonthlyCharges  TotalCharges  Churn  \
0           0              0           29.85         29.85      0   
1           1              0           56.95       1889.50      0   
2           2              0           53.85        108.15      1   
3           3              0           42.30       1840.75      0   
4           4              0           70.70        151.65      1   

   gender_Female  gender_Male  Partner_No  Partner_Yes  Dependents_No  ...  \
0           True        False       False         True           True  ...   
1          False         True        True        False           True  ...   
2          False         True        True        False           True  ...   
3          False         True        True        False           True  ...   
4           True        False        True        False           True  ...   

   PaymentMethod_Bank transfer (automatic)  \
0                                    False   
1                                    False   
2                                    False   
3                                     True   
4                                    False   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                  False                            True   
1                                  False                           False   
2                                  False                           False   
3                                  False                           False   
4                                  False                            True   

   PaymentMethod_Mailed check  tenure_group_1 - 12  tenure_group_13 - 24  \
0                       False                 True                 False   
1                        True                False                 False   
2                        True                 True                 False   
3                       False                False                 False   
4                       False                 True                 False   

   tenure_group_25 - 36  tenure_group_37 - 48  tenure_group_49 - 60  \
0                 False                 False                 False   
1                  True                 False                 False   
2                 False                 False                 False   
3                 False                  True                 False   
4                 False                 False                 False   

   tenure_group_61 - 72  
0                 False  
1                 False  
2                 False  
3                 False  
4                 False  

[5 rows x 52 columns]

In [5]:

df=df.drop('Unnamed: 0',axis=1)

In [6]:
x=df.drop('Churn',axis=1)
x

SeniorCitizen  MonthlyCharges  TotalCharges  gender_Female  gender_Male  \
0                 0           29.85         29.85           True        False   
1                 0           56.95       1889.50          False         True   
2                 0           53.85        108.15          False         True   
3                 0           42.30       1840.75          False         True   
4                 0           70.70        151.65           True        False   
...             ...             ...           ...            ...          ...   
7027              0           84.80       1990.50          False         True   
7028              0          103.20       7362.90           True        False   
7029              0           29.60        346.45           True        False   
7030              1           74.40        306.60          False         True   
7031              0          105.65       6844.50          False         True   

      Partner_No  Partner_Yes  Dependents_No  Dependents_Yes  PhoneService_No  \
0          False         True           True           False             True   
1           True        False           True           False            False   
2           True        False           True           False            False   
3           True        False           True           False             True   
4           True        False           True           False            False   
...          ...          ...            ...             ...              ...   
7027       False         True          False            True            False   
7028       False         True          False            True            False   
7029       False         True          False            True             True   
7030       False         True           True           False            False   
7031        True        False           True           False            False   

      ...  PaymentMethod_Bank transfer (automatic)  \
0     ...                                    False   
1     ...                                    False   
2     ...                                    False   
3     ...                                     True   
4     ...                                    False   
...   ...                                      ...   
7027  ...                                    False   
7028  ...                                    False   
7029  ...                                    False   
7030  ...                                    False   
7031  ...                                     True   

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                     False                            True   
1                                     False                           False   
2                                     False                           False   
3                                     False                           False   
4                                     False                            True   
...                                     ...                             ...   
7027                                  False                           False   
7028                                   True                           False   
7029                                  False                            True   
7030                                  False                           False   
7031                                  False                           False   

      PaymentMethod_Mailed check  tenure_group_1 - 12  tenure_group_13 - 24  \
0                          False                 True                 False   
1                           True                False                 False   
2                           True                 True                 False   
3                          False                False                 False   
4                          False                 True              

In [7]:
y=df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [9]:
model_dt=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [10]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [11]:
y_pred=model_dt.predict(x_test)
y_pred

array([0, 0, 1, ..., 0, 0, 0])

In [12]:
model_dt.score(x_test,y_test)

0.8045486851457001

In [13]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.85      0.90      0.87      1044
           1       0.64      0.54      0.59       363

    accuracy                           0.80      1407
   macro avg       0.75      0.72      0.73      1407
weighted avg       0.80      0.80      0.80      1407



In [14]:
from imblearn.combine import SMOTEENN

sm = SMOTEENN()
X_resampled, y_resampled = sm.fit_resample(x, y)

In [15]:
xr_train,xr_test,yr_train,yr_test=train_test_split(X_resampled, y_resampled,test_size=0.2)

In [16]:
model_dt_smote=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [17]:
model_dt_smote.fit(xr_train,yr_train)
yr_predict = model_dt_smote.predict(xr_test)
model_score_r = model_dt_smote.score(xr_test, yr_test)
print(model_score_r)
print(metrics.classification_report(yr_test, yr_predict))

0.9479522184300341
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       496
           1       0.95      0.96      0.95       676

    accuracy                           0.95      1172
   macro avg       0.95      0.95      0.95      1172
weighted avg       0.95      0.95      0.95      1172



In [18]:
print(metrics.confusion_matrix(yr_test, yr_predict))

[[465  31]
 [ 30 646]]


In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
model_rf=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)


In [21]:
model_rf.fit(x_train,y_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [24]:
y_pred=model_rf.predict(x_test)

In [23]:
model_rf.score(x_test,y_test)

0.8088130774697939

In [25]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.84      0.92      0.88      1044
           1       0.67      0.50      0.58       363

    accuracy                           0.81      1407
   macro avg       0.76      0.71      0.73      1407
weighted avg       0.80      0.81      0.80      1407



In [26]:
from imblearn.combine import SMOTEENN

sm = SMOTEENN()
X_resampled1, y_resampled1 = sm.fit_resample(x, y)

In [27]:
xr_train1,xr_test1,yr_train1,yr_test1=train_test_split(X_resampled1, y_resampled1,test_size=0.2)

In [28]:
model_rf_smote=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [29]:
model_rf_smote.fit(xr_train1,yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [30]:
yr_predict1 = model_rf_smote.predict(xr_test1)

In [31]:
model_score_r1 = model_rf_smote.score(xr_test1, yr_test1)


In [32]:
print(model_score_r1)
print(metrics.classification_report(yr_test1, yr_predict1))

0.9274124679760888
              precision    recall  f1-score   support

           0       0.93      0.90      0.91       504
           1       0.93      0.95      0.94       667

    accuracy                           0.93      1171
   macro avg       0.93      0.92      0.93      1171
weighted avg       0.93      0.93      0.93      1171



In [33]:
print(metrics.confusion_matrix(yr_test1, yr_predict1))


[[454  50]
 [ 35 632]]


Performing PCA:-


In [34]:
from sklearn.decomposition import PCA
pca = PCA(0.9)
xr_train_pca = pca.fit_transform(xr_train1)
xr_test_pca = pca.transform(xr_test1)
explained_variance = pca.explained_variance_ratio_

In [35]:
model=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [36]:
model.fit(xr_train_pca,yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [37]:
yr_predict_pca = model.predict(xr_test_pca)

In [38]:
model_score_r_pca = model.score(xr_test_pca, yr_test1)

In [40]:
print(model_score_r_pca)
print(metrics.classification_report(yr_test1, yr_predict_pca))

0.7438087105038429
              precision    recall  f1-score   support

           0       0.73      0.64      0.68       504
           1       0.75      0.82      0.78       667

    accuracy                           0.74      1171
   macro avg       0.74      0.73      0.73      1171
weighted avg       0.74      0.74      0.74      1171



In [47]:
import pickle

In [49]:
model_rf_smote.fit(xr_train1,yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [50]:
filename = 'model.sav'

In [51]:
pickle.dump(model_rf_smote, open(filename, 'wb'))

In [52]:
load_model = pickle.load(open(filename, 'rb'))

In [53]:
model_score_r1 = load_model.score(xr_test1, yr_test1)

In [55]:
model_score_r1

0.9274124679760888